name = "pagefind-docs-template"
license = "MIT"
licenselink = ""
description = "A docs template for Pagefind and Toolproof"
homepage = "https://github.com/pagefind/"
tags = []
features = []
min_version = "0.41.0"

[author]
name = "Liam Bigelow"
